Repository SoloJeju/front, pull requests merged in 2025-09, with the labels that each got.

#51 Modify/search detail UI
  package.json
  pnpm-lock.yaml
  src/assets/Star.svg
  src/assets/StarEmpty.svg
  src/assets/receipt.svg
  src/components/SearchPage/ReviewCard.tsx
  src/components/SearchPage/ReviewList.tsx
  src/components/SearchPage/ReviewStats.tsx
  src/pages/search-page/search-detail-page.tsx
Labels: 🎨design, 🔴priority:High

#56 Modify/review component
  src/components/SearchPage/KaKaoMap.tsx
  src/components/SearchPage/ReviewCard.tsx
  src/pages/search-page/search-detail-page.tsx
Labels: 🎨design, 🟠priority:Medium

#68 Feat/map
  public/MapPin.png
  src/components/SearchPage/KaKaoMap.tsx
  src/components/SearchPage/PlaceList.tsx
  src/pages/search-page/index.tsx
  src/pages/search-page/search-detail-page.tsx
  src/pages/search-page/search-map-page.tsx
Labels: ✨feature, 🔴priority:High

#71 Feat: 관광지 리스트 조회 & 검색 api 연결
  src/apis/tourist.ts
  src/assets/type-all.svg
  src/assets/type-bed.svg
  src/assets/type-course.svg
  src/assets/type-culture.svg
  src/assets/type-festival.svg
  src/assets/type-food.svg
  src/assets/type-leports.svg
  src/assets/type-shopping.svg
  src/assets/type-tourist.svg
  src/components/SearchPage/DifficultyFilter.tsx
  src/components/SearchPage/PlaceCard.tsx
  src/components/SearchPage/PlaceList.tsx
  src/constants/contentTypes.ts
  src/hooks/tourist/useGetTouristList.ts
  src/hooks/tourist/useSearchTourist.ts
  src/pages/search-page/index.tsx
  src/pages/search-page/search-box-page.tsx
  src/types/tourist.ts
Labels: ✨feature, 🔴priority:High

#73 Refactor: 동행방 생성 api 연결 수정
  src/apis/room.ts
  src/assets/alarmIcon.svg
  src/assets/category-all.svg
  src/assets/category-bed.svg
  src/assets/category-course.svg
  src/assets/category-culture.svg
  src/assets/category-festival.svg
  src/assets/category-food.svg
  src/assets/category-leisure.svg
  src/assets/category-shopping.svg
  src/assets/category-travel.svg
  src/components/Plus/TimePannel.tsx
  src/components/SearchPage/FliterBar.tsx
  src/components/common/Headers/AlarmHeader.tsx
  src/pages/plus-page/create-room-page.tsx
  src/pages/safety-check-page/index.tsx
  src/pages/search-page/search-box-page.tsx
  src/stores/createroom-store.ts
  src/types/tourist.ts
Labels: 💡refactor, 🔴priority:High

#83 Feat: plan api 연결
  src/App.tsx
  src/apis/mypage.ts
  src/apis/plan.ts
  src/assets/cartAdd.svg
  src/assets/memoIcon.svg
  src/assets/searchIcon.svg
  src/components/CartPage/PlaceCard.tsx
  src/components/CartPage/PlaceCardList.tsx
  src/components/Plus/Plan/EditPlanModal.tsx
  src/components/Plus/Plan/MemoModal.tsx
  src/components/Plus/Plan/PlaceCard.tsx
  src/components/Plus/Plan/TimeRangePicker.tsx
  src/components/SearchPage/PlaceCard.tsx
  src/components/SearchPage/PlaceList.tsx
  src/layouts/protected-layout.tsx
  src/pages/my-page/MyPlans.tsx
  src/pages/plus-page/create-room-page.tsx
  src/pages/plus-page/plan-ai-page.tsx
  src/pages/plus-page/plan-detail-page.tsx
  src/pages/plus-page/plan-page.tsx
  src/pages/plus-page/write-review-page.tsx
  src/pages/search-page/cart-page.tsx
  src/pages/search-page/search-box-page.tsx
  src/stores/plan-store.ts
  src/types/cart.ts
  src/types/mypage.ts
  src/types/plan.ts
  src/types/tourist.ts
Labels: ✨feature, 🔴priority:High

#104 Feat/map api
  package.json
  pnpm-lock.yaml
  public/markers/MapPin.png
  public/markers/type-all.png
  public/markers/type-bed.png
  public/markers/type-course.png
  public/markers/type-culture.png
  public/markers/type-festival.png
  public/markers/type-food.png
  public/markers/type-leports.png
  public/markers/type-shopping.png
  public/markers/type-tourist.png
  src/apis/searchmap.ts
  src/components/SearchPage/FliterBar.tsx
  src/components/SearchPage/KaKaoMap.tsx
  src/constants/contentTypes.ts
  src/pages/search-page/index.tsx
  src/pages/search-page/search-map-page.tsx
  src/types/kakao.d.ts
  src/types/searchmap.ts
Labels: ✨feature, 🔴priority:High

#118 design: 관광지 이미지 없음 처리 & 탐색페이지 타입 아이콘 오류 수정
  src/assets/ex-place.png
  src/assets/ex-place.svg
  src/assets/exampleImage.png
  src/assets/exampleImage.svg
  src/assets/loading.gif
  src/components/CartPage/PlaceCard.tsx
  src/components/SearchPage/PlaceCard.tsx
  src/components/Signup/steps/EmailStep.tsx
  src/components/Signup/steps/IntroStep.tsx
  src/components/Signup/steps/PasswordStep.tsx
  src/components/Signup/steps/ProfileInfoStep.tsx
  src/components/Signup/steps/QuestionStep.tsx
  src/components/Signup/steps/ResultStep.tsx
  src/constants/contentTypes.ts
  src/pages/my-page/MyBookmarks.tsx
  src/pages/my-page/MyComments.tsx
  src/pages/my-page/MyPlans.tsx
  src/pages/my-page/MyPosts.tsx
  src/pages/plus-page/plan-page.tsx
  src/pages/room-page/index.tsx
  src/pages/search-page/search-detail-page.tsx
Labels: 🎨design

#135 fix: 지도에서 상세 페이지 정보 로딩 에러 수정
  src/components/SearchPage/KaKaoMap.tsx
  src/pages/search-page/search-detail-page.tsx
  src/pages/search-page/search-map-page.tsx
Labels: 🔴priority:High
